# -*- coding: utf-8 -*-
"""DS_bootcamp_week1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q8yfL-L7HvRYrur5Ukpd_FJGJjElaCzD
"""

# Display Fibonacci Series upto 10 terms

fibonacci_numbers = []

# Adding the first two fibonacci numbers to the list
fibonacci_numbers.append(0)
fibonacci_numbers.append(1)

for i in range(2, 10):
    fibonacci_numbers.append(fibonacci_numbers[i-1] + fibonacci_numbers[i-2])

for number in fibonacci_numbers:
    print(number)

# Display numbers at the odd indices of a list

numbers_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
print("List: ", numbers_list)

print()
print("Numbers at Odd Indices of the list: ")

for i in range(len(numbers_list)):
    if i % 2 != 0:
        print(numbers_list[i])

import re

# Given text
string = """
I have provided this text to provide tips on creating interesting paragraphs.

First, start with a clear topic sentence that introduces the main idea.

Then, support the topic sentence with specific details, examples, and evidence.

Vary the sentence length and structure to keep the reader engaged.

Finally, end with a strong concluding sentence that summarizes the main points.

Remember, practice makes perfect!
"""

# Normalize text: convert to lowercase and extract words using regex
word_list = re.findall(r'\b\w+\b', string.lower())

# Get unique words
unique_words = set(word_list)

# Print the number of different words
print("Number of different words:", len(unique_words))

# Print unique words
print("\nUnique words:", unique_words)

def count_vowels(word):
    vowels = set("aeiouAEIOU")  # Using a set for faster lookup
    return sum(1 for char in word if char in vowels)  # Count vowels in the word

word = input("Enter a word: ")  # Takes user input
print(f"Number of vowels in '{word}' is: {count_vowels(word)}")

animals = ['tiger', 'elephant', 'monkey', 'zebra', 'panther']

# Iterate and print each animal in uppercase
for animal in animals:
    print(animal.upper())

def check_odd_even():
    for num in range(1, 21):  # Loop from 1 to 20
        if num % 2 == 0:
            print(f"{num} is Even")
        else:
            print(f"{num} is Odd")

# Call the function
check_odd_even()

def sum_of_integers(a, b):
    return a + b  # Returns the sum of two integers

# Taking input from the user
num1 = int(input("Enter the first integer: "))
num2 = int(input("Enter the second integer: "))

# Calling the function and printing the result
print(f"The sum of {num1} and {num2} is: {sum_of_integers(num1, num2)}")